SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS sed_student;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE IF NOT EXISTS sed_student (
  id      BIGINT      NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNIQUE,
  course  VARCHAR(10) NOT NULL,
  student_group VARCHAR(10) NOT NULL,

  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES sed_user (id)
    ON DELETE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARSET =utf8;